version: '3'
networks:
  data:
services:
  bot:
    image: node:17.7.1
    container_name: crypto-bot
    volumes:
      - ./bot:/bot
    command: bash -c "npm install -g pm2 typescript && cd /bot && npm install && tsc && pm2-runtime start ecosystem.config.js"
    environment:
      - DB_URI=mongodb://db:27017/crypto-bot
    depends_on:
      - db
    networks:
      - data
  db:
    image: mongo:5.0.6
    container_name: mongo-crypto
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017-27019:27017-27019
    networks:
      - data
